CREATE DATABASE ECOMMERCE
go
USE ECOMMERCE
GO
CREATE TABLE USUARIOS(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR (100) NULL, 
APELLIDO VARCHAR (100) NULL, 
EMAIL VARCHAR (100) NULL, 
CONTRASEÑA VARCHAR(100) NULL 
)
GO 
CREATE TABLE MARCAS (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
NOMBRE VARCHAR (100) NOT NULL
)
GO
CREATE TABLE TIPOS (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
NOMBRE VARCHAR (100)
)
GO
CREATE TABLE COLORES (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
NOMBRE VARCHAR (100) NOT NULL
)
GO
CREATE TABLE PRODUCTOS(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
NOMBRE VARCHAR(100) NOT NULL, 
DESCRIPCION VARCHAR (200) NULL, 
IDTIPO INT NOT NULL FOREIGN KEY REFERENCES TIPOS(ID),
IDMARCA INT FOREIGN KEY REFERENCES MARCAS (ID),
IMAGEN VARCHAR (500) NULL,
PRECIO MONEY NULL
)
GO
CREATE TABLE COLORES_X_PRODUCTO (
IDPRODUCTO INT FOREIGN KEY REFERENCES PRODUCTOS(ID), 
IDCOLOR INT FOREIGN KEY REFERENCES COLORES (ID),
STOCK INT NOT NULL DEFAULT 0
)
GO
CREATE TABLE VENTAS (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
IDUSUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID),
PRECIOTOTAL MONEY DEFAULT 0
)
GO 
CREATE TABLE DETALLE_VENTA (
IDVENTA INT FOREIGN KEY REFERENCES VENTAS (ID), 
IDPRODUCTO INT FOREIGN KEY REFERENCES PRODUCTOS (ID), 
CANTIDAD INT NOT NULL, 
PRECIO MONEY NOT NULL
)


-- ****************** PROCEDIMIENTOS ALMACENADOS ******************
Go
CREATE PROCEDURE SP_AGREGARPRODUCTO (
@Nombre varchar (100), 
@Descripcion varchar (200), 
@Tipo int, 
@Marca int, 
@Imagen varchar (500), 
@Precio money
)AS
BEGIN 
	INSERT INTO PRODUCTOS VALUES(@Nombre,@Descripcion, @Tipo, @Marca, @Imagen, @Precio)
	
END 

Go
CREATE PROCEDURE SP_AGREGARCOLOR_x_PRODUCTO (
@IdProducto int, 
@IdColor int, 
@Stock int
)AS
BEGIN 
	INSERT INTO COLORES_X_PRODUCTO VALUES(@IdProducto, @IdColor,@Stock)
	
END 

Go
CREATE PROCEDURE SP_AGREGARMARCA (
@Nombre varchar (100)
)AS
BEGIN 
	INSERT INTO MARCAS VALUES(@Nombre)
	
END 

Go
CREATE PROCEDURE SP_AGREGARTIPO (
@Nombre varchar (100)
)AS
BEGIN 
	INSERT INTO TIPOS VALUES(@Nombre)
	
END



